---
title: JIGEEN - I'M A WOMEN I'M SUPERHUMAN
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  sliders:
    title: Sliders
    output: true
  uploads:
    title: Uploads
    output: true
  categories:
    title: categories
    output: true
email: contact@jigeen.com
tel: "+221 77 452 87 06"
description: 'Je reussirais dans certaines taches mieux que dans d''autres mais au
  moins j''essaie de tout faire. I''m a women, I''m superhuman

'
baseurl: ''
url: ''
twitter_username: jekyllrb
github_username: jekyll
markdown: kramdown
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
